import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, onSnapshot, runTransaction } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';

// Battleground 2.5D — Etapa 3 · continuidad desde Work.
// Reglas aplicadas:
// - Un dominio: capacidad máxima Agua 30.
// - Cantidad actual y capacidad máxima son estados distintos.
// - Gastar Agua deja huecos vacíos; solo tiempo/cristal los rellena.
// - Máximo 6 invocaciones activas por jugador.
// - Al resolver kasteo la invocación se materializa y sincroniza en Arena.

const FIREBASE_CONFIG={apiKey:'AIzaSyCapopKSADRBnhk7wZVWKcnFG__zl3TYnw',authDomain:'rok-rise-of-caster.firebaseapp.com',projectId:'rok-rise-of-caster',storageBucket:'rok-rise-of-caster.firebasestorage.app',messagingSenderId:'147189629810',appId:'1:147189629810:web:3bebec7a294902545d93eb'};
const COLLECTION='battleground_stage3_patch_rooms';
const WATER_MAX=30,SUMMON_MAX=6,RECHARGE_MS=3000,CAST_MS=4000,CRYSTAL_RESPAWN_MS=12000,MOVE_STEP=.55,ARENA_X=5.2,ARENA_Z=8.1,SUMMON_COST=2;
const CRYSTAL_SEEDS=[[-3.4,-4.8],[0,-5.4],[3.4,-4.8],[-4.1,-1.7],[-1.4,-1.5],[1.4,-1.5],[4.1,-1.7],[-3.5,1.8],[0,1.45],[3.5,1.8],[-3.2,4.9],[0,5.4],[3.2,4.9]];
const ids=['arena','lobbyPanel','createRoomBtn','roomCodeInput','joinRoomBtn','lobbyInfo','lobbyError','roomBadge','invocationCounter','resourceClock','toast','spellbookToggle','spellbookPanel','spellbookSlotInfo','waterInvocationCard','spellbookMessage','closeSpellbookBtn','castStrip','castText','castFill','p1Pips','p2Pips','p1Water','p2Water','p1WaterMeter','p2WaterMeter','p1Life','p2Life','p1LifeFill','p2LifeFill'];
const els=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
for(const holder of [els.p1Pips,els.p2Pips]){holder.innerHTML='';for(let i=0;i<WATER_MAX;i++)holder.appendChild(document.createElement('i'))}
const canvas=els.arena,ctx=canvas.getContext('2d'),clientId=getClientId();
let db=null,auth=null,roomRef=null,roomCode='',slot=null,roomState=null,unsub=null,localTimer=null,toastTimer=null,keyGate=0;
const app=initializeApp(FIREBASE_CONFIG);db=getFirestore(app);auth=getAuth(app);bootstrapNetwork();

function getClientId(){const k='rok_battleground_stage3_client';let id=localStorage.getItem(k);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random()}`;localStorage.setItem(k,id)}return id}
async function bootstrapNetwork(){try{await signInAnonymously(auth)}catch(err){console.warn('Anonymous auth unavailable; continuing with Firestore rules as configured.',err)}}
function makePlayer(which,id){return{clientId:id,life:20,water:0,maxWater:WATER_MAX,x:0,z:which==='p1'?6.35:-6.35,summons:[],casting:null,castStartedAt:0,castEndAt:0,lastRechargeAt:Date.now()}}
function makeCrystals(){const out={};CRYSTAL_SEEDS.forEach((p,i)=>out[`c${i+1}`]={id:`c${i+1}`,x:p[0],z:p[1],active:true,respawnAt:0});return out}
function makeRoom(code){return{code,version:'etapa3-resource-30-summon-6',createdAt:Date.now(),updatedAt:Date.now(),players:{p1:makePlayer('p1',clientId),p2:null},crystals:makeCrystals()}}
function randomCode(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=a[Math.floor(Math.random()*a.length)];return s}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function meFrom(r=roomState){return r?.players?.[slot]||null}

els.roomCodeInput.addEventListener('input',()=>{const v=els.roomCodeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);els.roomCodeInput.value=v;els.joinRoomBtn.disabled=v.length!==6});
els.createRoomBtn.addEventListener('click',createRoom);els.joinRoomBtn.addEventListener('click',()=>joinRoom(els.roomCodeInput.value));
els.spellbookToggle.addEventListener('click',()=>setSpellbook(true));els.closeSpellbookBtn.addEventListener('click',()=>setSpellbook(false));els.waterInvocationCard.addEventListener('click',startSummonCast);
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='b'&&slot){setSpellbook(els.spellbookPanel.classList.contains('hidden'));return}if(['w','a','s','d'].includes(k)){e.preventDefault();moveByKey(k)}});
document.querySelectorAll('.touch-controls button').forEach(btn=>btn.addEventListener('pointerdown',e=>{e.preventDefault();moveByKey(btn.dataset.key)}));

async function createRoom(){setLobbyBusy(true);clearLobbyError();const code=randomCode();try{roomRef=doc(db,COLLECTION,code);const snap=await getDoc(roomRef);if(snap.exists()){setLobbyBusy(false);return createRoom()}await setDoc(roomRef,makeRoom(code));slot='p1';roomCode=code;startRoomSubscription();enterArena()}catch(err){console.error(err);setLobbyBusy(false);showLobbyError('No se pudo crear la sala. Verifica conexión/Firebase.')}}
async function joinRoom(codeRaw){const code=String(codeRaw||'').trim().toUpperCase();if(code.length!==6)return;setLobbyBusy(true);clearLobbyError();try{roomRef=doc(db,COLLECTION,code);await runTransaction(db,async tx=>{const snap=await tx.get(roomRef);if(!snap.exists())throw new Error('ROOM_NOT_FOUND');const r=snap.data();if(r.players?.p2?.clientId&&r.players.p2.clientId!==clientId)throw new Error('ROOM_FULL');tx.update(roomRef,{'players.p2':r.players?.p2||makePlayer('p2',clientId),updatedAt:Date.now()})});slot='p2';roomCode=code;startRoomSubscription();enterArena()}catch(err){console.error(err);setLobbyBusy(false);showLobbyError(err.message==='ROOM_NOT_FOUND'?'Sala no encontrada.':err.message==='ROOM_FULL'?'La sala ya tiene dos jugadores.':'No se pudo unir a la sala.')}}
function setLobbyBusy(v){els.createRoomBtn.disabled=v;els.joinRoomBtn.disabled=v||els.roomCodeInput.value.length!==6;els.lobbyInfo.textContent=v?'Conectando…':'W/S: profundidad · D: avanzar · A: retroceder'}
function clearLobbyError(){els.lobbyError.textContent=''}function showLobbyError(t){els.lobbyError.textContent=t}
function startRoomSubscription(){if(unsub)unsub();unsub=onSnapshot(roomRef,snap=>{if(!snap.exists())return;roomState=snap.data();renderHud();renderSpellbookState();maybeCollectCrystal()},err=>{console.error(err);showToast('Conexión de sala interrumpida')});clearInterval(localTimer);localTimer=setInterval(async()=>{await tickRecharge();await tickCast();await tickCrystalRespawn()},500)}
function enterArena(){els.lobbyPanel.hidden=true;els.roomBadge.hidden=false;els.invocationCounter.hidden=false;els.resourceClock.hidden=false;els.spellbookToggle.classList.remove('hidden');els.roomBadge.textContent=`SALA ${roomCode} · ${slot==='p1'?'KASTER I':'KASTER II'}`;setLobbyBusy(false);showToast(slot==='p1'?`Sala ${roomCode} creada`:`Unido a ${roomCode}`)}
function setSpellbook(open){if(!slot)return;els.spellbookPanel.classList.toggle('hidden',!open);els.spellbookToggle.classList.toggle('hidden',open)}

async function moveByKey(key){if(!roomRef||!slot||!roomState||Date.now()<keyGate)return;keyGate=Date.now()+45;const p=meFrom();if(!p)return;let x=p.x||0,z=p.z||0;if(key==='w')x-=MOVE_STEP;if(key==='s')x+=MOVE_STEP;const dir=slot==='p1'?-1:1;if(key==='d')z+=MOVE_STEP*dir;if(key==='a')z-=MOVE_STEP*dir;x=clamp(x,-ARENA_X,ARENA_X);z=clamp(z,-ARENA_Z,ARENA_Z);roomState.players[slot]={...p,x,z};try{await updateDoc(roomRef,{[`players.${slot}.x`]:x,[`players.${slot}.z`]:z,updatedAt:Date.now()})}catch(err){console.warn('movement sync failed',err)}maybeCollectCrystal()}

async function tickRecharge(){if(!roomRef||!slot||!roomState)return;const p=meFrom();if(!p)return;const now=Date.now(),last=Number(p.lastRechargeAt||now);els.resourceClock.textContent=p.water>=WATER_MAX?'AGUA ◆ LLENA':`RECARGA ◆ ${Math.max(0,(RECHARGE_MS-(now-last))/1000).toFixed(1)}s`;if(now-last<RECHARGE_MS)return;try{await runTransaction(db,async tx=>{const snap=await tx.get(roomRef);if(!snap.exists())return;const r=snap.data(),q=r.players?.[slot];if(!q)return;const t=Date.now(),qLast=Number(q.lastRechargeAt||t),elapsed=t-qLast;if(elapsed<RECHARGE_MS)return;const steps=Math.max(1,Math.floor(elapsed/RECHARGE_MS)),current=clamp(Number(q.water||0),0,WATER_MAX),next=Math.min(WATER_MAX,current+steps),nextLast=current>=WATER_MAX?t:qLast+steps*RECHARGE_MS;tx.update(roomRef,{[`players.${slot}.water`]:next,[`players.${slot}.maxWater`]:WATER_MAX,[`players.${slot}.lastRechargeAt`]:nextLast,updatedAt:t})})}catch(err){console.warn('recharge sync failed',err)}}
async function maybeCollectCrystal(){if(!roomRef||!slot||!roomState)return;const p=meFrom();if(!p||Number(p.water||0)>=WATER_MAX)return;for(const c of Object.values(roomState.crystals||{})){if(!c.active)continue;if(Math.hypot((p.x||0)-c.x,(p.z||0)-c.z)<=.72){await collectCrystal(c.id);break}}}
async function collectCrystal(id){try{await runTransaction(db,async tx=>{const snap=await tx.get(roomRef);if(!snap.exists())return;const r=snap.data(),p=r.players?.[slot],c=r.crystals?.[id];if(!p||!c||!c.active)return;if(Math.hypot((p.x||0)-c.x,(p.z||0)-c.z)>.85)return;if(Number(p.water||0)>=WATER_MAX)return;const now=Date.now();tx.update(roomRef,{[`players.${slot}.water`]:Math.min(WATER_MAX,Number(p.water||0)+1),[`crystals.${id}.active`]:false,[`crystals.${id}.respawnAt`]:now+CRYSTAL_RESPAWN_MS,updatedAt:now})});showToast('+1 Agua por cristal')}catch(err){console.warn('crystal collection failed',err)}}
async function tickCrystalRespawn(){if(!roomRef||!roomState)return;const due=Object.values(roomState.crystals||{}).find(c=>!c.active&&c.respawnAt&&Date.now()>=c.respawnAt);if(!due)return;try{await runTransaction(db,async tx=>{const snap=await tx.get(roomRef);if(!snap.exists())return;const c=snap.data().crystals?.[due.id];if(!c||c.active||Date.now()<Number(c.respawnAt||0))return;tx.update(roomRef,{[`crystals.${due.id}.active`]:true,[`crystals.${due.id}.respawnAt`]:0,updatedAt:Date.now()})})}catch(err){console.warn('crystal respawn failed',err)}}

async function startSummonCast(){if(!roomRef||!slot||!roomState)return;const p=meFrom();if(!p)return;if((p.summons||[]).length>=SUMMON_MAX){showToast('Límite de 6 invocaciones en Arena');return}if(p.casting){showToast('Ya hay una invocación kasteándose');return}if(Number(p.water||0)<SUMMON_COST){showToast('Necesitas 2 Agua');return}const now=Date.now();try{await runTransaction(db,async tx=>{const snap=await tx.get(roomRef);if(!snap.exists())return;const r=snap.data(),q=r.players?.[slot];if(!q)return;if((q.summons||[]).length>=SUMMON_MAX)throw new Error('SUMMON_LIMIT');if(q.casting)throw new Error('ALREADY_CASTING');if(Number(q.water||0)<SUMMON_COST)throw new Error('NO_WATER');tx.update(roomRef,{[`players.${slot}.water`]:Number(q.water)-SUMMON_COST,[`players.${slot}.casting`]:'waterInvocation',[`players.${slot}.castStartedAt`]:now,[`players.${slot}.castEndAt`]:now+CAST_MS,updatedAt:now})});setSpellbook(false);showToast('Kasteo iniciado · -2 Agua')}catch(err){if(err.message==='SUMMON_LIMIT')showToast('Límite de 6 invocaciones en Arena');else if(err.message==='NO_WATER')showToast('Necesitas 2 Agua');else console.warn(err)}}
async function tickCast(){if(!roomRef||!slot||!roomState)return;const p=meFrom();if(!p?.casting){els.castStrip.classList.add('hidden');return}const now=Date.now(),start=Number(p.castStartedAt||now),end=Number(p.castEndAt||now),progress=clamp((now-start)/Math.max(1,end-start),0,1);els.castStrip.classList.remove('hidden');els.castText.textContent=`KASTEANDO INVOCACIÓN DE AGUA · ${Math.max(0,(end-now)/1000).toFixed(1)}s`;els.castFill.style.width=`${progress*100}%`;if(now<end)return;try{await runTransaction(db,async tx=>{const snap=await tx.get(roomRef);if(!snap.exists())return;const r=snap.data(),q=r.players?.[slot];if(!q?.casting||Date.now()<Number(q.castEndAt||0))return;const summons=Array.isArray(q.summons)?[...q.summons]:[];if(summons.length>=SUMMON_MAX){tx.update(roomRef,{[`players.${slot}.casting`]:null,[`players.${slot}.castStartedAt`]:0,[`players.${slot}.castEndAt`]:0,updatedAt:Date.now()});return}const index=summons.length,dir=slot==='p1'?-1:1,offsets=[[-1.2,0],[1.2,0],[-2.1,.55],[2.1,.55],[-.7,1.1],[.7,1.1]],off=offsets[index]||[0,index*.35];summons.push({id:`${slot}_summon_${Date.now()}_${Math.floor(Math.random()*9999)}`,name:'Invocación de Agua',x:clamp(Number(q.x||0)+off[0],-ARENA_X,ARENA_X),z:clamp(Number(q.z||0)+off[1]*dir,-ARENA_Z,ARENA_Z),spawnedAt:Date.now(),life:3});tx.update(roomRef,{[`players.${slot}.summons`]:summons,[`players.${slot}.casting`]:null,[`players.${slot}.castStartedAt`]:0,[`players.${slot}.castEndAt`]:0,updatedAt:Date.now()})});showToast('Invocación materializada en Arena')}catch(err){console.warn('cast resolution failed',err)}}

function renderHud(){const p1=roomState?.players?.p1||makePlayer('p1',''),p2=roomState?.players?.p2||makePlayer('p2','');setWater('p1',Number(p1.water||0));setWater('p2',Number(p2.water||0));setLife('p1',Number(p1.life||20));setLife('p2',Number(p2.life||20));const me=meFrom();if(me){const n=(me.summons||[]).length;els.invocationCounter.textContent=`INVOCACIONES ${n}/${SUMMON_MAX}`;els.spellbookSlotInfo.textContent=`Invocaciones ${n}/${SUMMON_MAX}`}}
function setWater(which,value){value=clamp(value,0,WATER_MAX);const pips=which==='p1'?els.p1Pips:els.p2Pips;[...pips.children].forEach((p,i)=>p.classList.toggle('filled',i<value));const text=which==='p1'?els.p1Water:els.p2Water,meter=which==='p1'?els.p1WaterMeter:els.p2WaterMeter;text.textContent=`${value}/${WATER_MAX}`;meter.setAttribute('aria-label',`${value} de ${WATER_MAX} elementos de Agua`)}
function setLife(which,value){value=clamp(value,0,20);const t=which==='p1'?els.p1Life:els.p2Life,f=which==='p1'?els.p1LifeFill:els.p2LifeFill;t.textContent=String(value);f.style.width=`${value/20*100}%`}
function renderSpellbookState(){const p=meFrom();if(!p)return;const n=(p.summons||[]).length;els.waterInvocationCard.disabled=!!p.casting||n>=SUMMON_MAX||Number(p.water||0)<SUMMON_COST;if(n>=SUMMON_MAX)els.spellbookMessage.textContent='Arena llena: 6/6 invocaciones.';else if(p.casting)els.spellbookMessage.textContent='Kasteo en curso. Al completarse, la invocación aparecerá en Arena.';else els.spellbookMessage.textContent='Máximo 6 invocaciones activas en Arena.'}
function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('show'),1700)}

function resizeCanvas(){const dpr=Math.min(window.devicePixelRatio||1,2),rect=canvas.getBoundingClientRect(),w=Math.max(320,Math.floor(rect.width*dpr)),h=Math.max(480,Math.floor(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0)}
window.addEventListener('resize',resizeCanvas);resizeCanvas();
function project(x,z,w=canvas.clientWidth,h=canvas.clientHeight){const t=clamp((z+ARENA_Z)/(ARENA_Z*2),0,1),y=h*.16+t*h*.73,halfFar=Math.min(w*.19,220),halfNear=Math.min(w*.46,520),half=halfFar+(halfNear-halfFar)*t;return{x:w/2+(x/ARENA_X)*half,y,scale:.48+t*.72,t}}
function drawArena(){const w=canvas.clientWidth,h=canvas.clientHeight,g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#06141a');g.addColorStop(.35,'#071115');g.addColorStop(1,'#020608');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const hz=ctx.createRadialGradient(w/2,h*.15,0,w/2,h*.18,w*.6);hz.addColorStop(0,'rgba(64,157,155,.15)');hz.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=hz;ctx.fillRect(0,0,w,h*.6);const farL=project(-ARENA_X,-ARENA_Z),farR=project(ARENA_X,-ARENA_Z),nearL=project(-ARENA_X,ARENA_Z),nearR=project(ARENA_X,ARENA_Z);ctx.beginPath();ctx.moveTo(farL.x,farL.y);ctx.lineTo(farR.x,farR.y);ctx.lineTo(nearR.x,nearR.y);ctx.lineTo(nearL.x,nearL.y);ctx.closePath();const floor=ctx.createLinearGradient(0,farL.y,0,nearL.y);floor.addColorStop(0,'#0c2726');floor.addColorStop(.5,'#132c2a');floor.addColorStop(1,'#182b29');ctx.fillStyle=floor;ctx.fill();ctx.strokeStyle='rgba(140,246,226,.12)';ctx.lineWidth=1;for(let i=-5;i<=5;i++){const a=project(i,-ARENA_Z),b=project(i,ARENA_Z);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let j=-8;j<=8;j++){const a=project(-ARENA_X,j),b=project(ARENA_X,j);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}const midA=project(-ARENA_X,0),midB=project(ARENA_X,0);ctx.strokeStyle='rgba(255,255,255,.24)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(midA.x,midA.y);ctx.lineTo(midB.x,midB.y);ctx.stroke()}
function drawCrystal(c){if(!c.active)return;const p=project(c.x,c.z),s=8*p.scale;ctx.save();ctx.translate(p.x,p.y-12*p.scale);ctx.rotate(Math.PI/4);ctx.shadowColor='#43c8ff';ctx.shadowBlur=18*p.scale;ctx.fillStyle='#93eaff';ctx.fillRect(-s/2,-s/2,s,s);ctx.fillStyle='rgba(255,255,255,.7)';ctx.fillRect(-s*.18,-s*.35,s*.2,s*.35);ctx.restore()}
function drawCaster(which,p){if(!p)return;const q=project(p.x||0,p.z||0),friendly=which===slot,r=13*q.scale;ctx.save();ctx.translate(q.x,q.y);ctx.shadowColor=friendly?'#67f3dc':'#ff6e73';ctx.shadowBlur=22*q.scale;ctx.fillStyle=friendly?'#bafff2':'#ffc0b5';ctx.beginPath();ctx.arc(0,-r*.7,r,0,Math.PI*2);ctx.fill();ctx.fillStyle=friendly?'#0f8072':'#8d2b36';ctx.fillRect(-r*.55,-r*.5,r*1.1,r*1.8);ctx.fillStyle='#fff';ctx.font=`${Math.max(8,9*q.scale)}px sans-serif`;ctx.textAlign='center';ctx.fillText(which==='p1'?'I':'II',0,-r*2.05);ctx.restore()}
function drawSummon(which,s,index){const q=project(s.x||0,s.z||0),friendly=which===slot,r=11*q.scale;ctx.save();ctx.translate(q.x,q.y-4*q.scale);ctx.shadowColor=friendly?'#38c8ff':'#ff875d';ctx.shadowBlur=16*q.scale;ctx.fillStyle=friendly?'#269fc7':'#b04b36';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=Math.max(1,q.scale);ctx.stroke();ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(7,8*q.scale)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(index+1),0,.5);ctx.restore()}
function draw(){resizeCanvas();ctx.save();drawArena();if(roomState){Object.values(roomState.crystals||{}).forEach(drawCrystal);const p1=roomState.players?.p1,p2=roomState.players?.p2;drawCaster('p1',p1);drawCaster('p2',p2);(p1?.summons||[]).forEach((s,i)=>drawSummon('p1',s,i));(p2?.summons||[]).forEach((s,i)=>drawSummon('p2',s,i))}ctx.restore();requestAnimationFrame(draw)}
requestAnimationFrame(draw);
